---
- hosts: "{{ sso_domain | default('all') }}"
  gather_facts: yes
  become: no
  serial: 1
  #strategy: debug

  vars:
    script_urls:
      checksts: https://kb.vmware.com/sfc/servlet.shepherd/version/download/068f400000HW9InAAL
      fixsts: https://kb.vmware.com/sfc/servlet.shepherd/version/download/068f400000HnqyiAAB

  tasks:
    - name: checksts
      include_role:
        name: check_sts
      when: sts_role == 'all'  or sts_role =='master'

    - name: Run fixsts.sh script
      include_role:
        name: fix_sts
      when: 
      - run_fix | default(false)
      - sts_role == 'all' or sts_role == 'master'

    - name: restart services on all/master sts
      include_role:
        name: restart_services
      when:
       - run_fix | default(false)
       - sts_role == restart_group
      with_items: "{{ restart_order }}"
      loop_control:
        loop_var: restart_group

---
- hosts: "{{ localhost }}"
  gather_facts: yes
  become: no
  serial: 1
  #strategy: debug

- name: send the report
  include_role:
    name: send_report
  when: send_report | default(False)